[2022-11-29T00:46:25.436+0000] {processor.py:156} INFO - Started process (PID=32124) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:46:25.439+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:46:25.440+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:46:25.439+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:46:25.464+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:46:25.463+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:46:25.464+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:46:25.482+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.048 seconds
[2022-11-29T00:46:55.767+0000] {processor.py:156} INFO - Started process (PID=32149) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:46:55.770+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:46:55.771+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:46:55.771+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:46:55.803+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:46:55.802+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:46:55.803+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:46:55.854+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.091 seconds
[2022-11-29T00:47:26.059+0000] {processor.py:156} INFO - Started process (PID=32181) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:47:26.062+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:47:26.064+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:47:26.064+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:47:26.109+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:47:26.107+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:47:26.111+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:47:26.137+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.082 seconds
[2022-11-29T00:47:56.385+0000] {processor.py:156} INFO - Started process (PID=32204) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:47:56.390+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:47:56.392+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:47:56.391+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:47:56.433+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:47:56.431+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:47:56.435+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:47:56.463+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.082 seconds
[2022-11-29T00:48:26.701+0000] {processor.py:156} INFO - Started process (PID=32236) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:48:26.706+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:48:26.707+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:48:26.707+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:48:26.750+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:48:26.748+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:48:26.751+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:48:26.774+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.077 seconds
[2022-11-29T00:48:57.041+0000] {processor.py:156} INFO - Started process (PID=32268) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:48:57.045+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:48:57.046+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:48:57.046+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:48:57.085+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:48:57.084+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:48:57.086+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:48:57.108+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.073 seconds
[2022-11-29T00:49:27.364+0000] {processor.py:156} INFO - Started process (PID=32291) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:49:27.367+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:49:27.368+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:49:27.368+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:49:27.413+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:49:27.411+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:49:27.414+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:49:27.436+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.076 seconds
[2022-11-29T00:49:57.680+0000] {processor.py:156} INFO - Started process (PID=32323) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:49:57.691+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:49:57.692+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:49:57.692+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:49:57.739+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:49:57.738+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:49:57.740+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:49:57.761+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.084 seconds
[2022-11-29T00:50:28.005+0000] {processor.py:156} INFO - Started process (PID=32355) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:50:28.012+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:50:28.013+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:50:28.013+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:50:28.053+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:50:28.052+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:50:28.054+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:50:28.078+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.075 seconds
[2022-11-29T00:50:58.373+0000] {processor.py:156} INFO - Started process (PID=32378) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:50:58.376+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:50:58.378+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:50:58.378+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:50:58.415+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:50:58.414+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:50:58.416+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:50:58.442+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.072 seconds
[2022-11-29T00:51:28.771+0000] {processor.py:156} INFO - Started process (PID=32410) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:51:28.776+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:51:28.777+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:51:28.777+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:51:28.818+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:51:28.817+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:51:28.819+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:51:28.843+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.075 seconds
[2022-11-29T00:51:59.058+0000] {processor.py:156} INFO - Started process (PID=32442) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:51:59.062+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:51:59.063+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:51:59.063+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:51:59.097+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:51:59.096+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:51:59.098+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:51:59.121+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T00:52:29.392+0000] {processor.py:156} INFO - Started process (PID=32465) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:52:29.396+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:52:29.397+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:52:29.397+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:52:29.423+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:52:29.422+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:52:29.424+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:52:29.438+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.049 seconds
[2022-11-29T00:52:59.619+0000] {processor.py:156} INFO - Started process (PID=32497) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:52:59.621+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:52:59.622+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:52:59.622+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:52:59.656+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:52:59.655+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:52:59.657+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:52:59.673+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.056 seconds
[2022-11-29T00:53:29.938+0000] {processor.py:156} INFO - Started process (PID=32529) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:53:29.942+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:53:29.943+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:53:29.943+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:53:29.982+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:53:29.981+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:53:29.983+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:53:30.005+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T00:54:00.224+0000] {processor.py:156} INFO - Started process (PID=32552) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:54:00.227+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:54:00.228+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:54:00.228+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:54:00.263+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:54:00.262+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:54:00.264+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:54:00.288+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T00:54:30.572+0000] {processor.py:156} INFO - Started process (PID=32584) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:54:30.575+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:54:30.575+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:54:30.575+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:54:30.607+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:54:30.606+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:54:30.607+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:54:30.626+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.057 seconds
[2022-11-29T00:55:00.837+0000] {processor.py:156} INFO - Started process (PID=32616) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:55:00.841+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:55:00.841+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:55:00.841+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:55:00.879+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:55:00.878+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:55:00.880+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:55:00.903+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T00:55:31.179+0000] {processor.py:156} INFO - Started process (PID=32639) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:55:31.181+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:55:31.182+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:55:31.182+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:55:31.219+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:55:31.218+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:55:31.220+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:55:31.239+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T00:56:01.417+0000] {processor.py:156} INFO - Started process (PID=32671) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:56:01.419+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:56:01.420+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:56:01.420+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:56:01.451+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:56:01.449+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:56:01.452+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:56:01.487+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.073 seconds
[2022-11-29T00:56:31.856+0000] {processor.py:156} INFO - Started process (PID=32703) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:56:31.859+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:56:31.861+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:56:31.860+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:56:31.896+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:56:31.894+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:56:31.897+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:56:31.917+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.064 seconds
[2022-11-29T00:57:02.146+0000] {processor.py:156} INFO - Started process (PID=32727) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:57:02.149+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:57:02.150+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:57:02.150+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:57:02.188+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:57:02.187+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:57:02.189+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:57:02.228+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.085 seconds
[2022-11-29T00:57:32.488+0000] {processor.py:156} INFO - Started process (PID=32759) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:57:32.491+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:57:32.492+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:57:32.492+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:57:32.529+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:57:32.527+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:57:32.530+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:57:32.553+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T00:58:02.807+0000] {processor.py:156} INFO - Started process (PID=323) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:58:02.810+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:58:02.812+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:58:02.812+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:58:02.851+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:58:02.850+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:58:02.852+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:58:02.880+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.077 seconds
[2022-11-29T00:58:33.185+0000] {processor.py:156} INFO - Started process (PID=346) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:58:33.189+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:58:33.190+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:58:33.190+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:58:33.230+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:58:33.229+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:58:33.231+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:58:33.275+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.093 seconds
[2022-11-29T00:59:03.489+0000] {processor.py:156} INFO - Started process (PID=378) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:59:03.493+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:59:03.494+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:59:03.494+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:59:03.532+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:59:03.529+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:59:03.533+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:59:03.594+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.108 seconds
[2022-11-29T00:59:33.848+0000] {processor.py:156} INFO - Started process (PID=410) to work on /opt/airflow/dags/create_db.py
[2022-11-29T00:59:33.851+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T00:59:33.852+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:59:33.852+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T00:59:33.891+0000] {logging_mixin.py:117} INFO - [2022-11-29T00:59:33.889+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T00:59:33.892+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T00:59:33.976+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.131 seconds
[2022-11-29T01:00:04.153+0000] {processor.py:156} INFO - Started process (PID=433) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:00:04.156+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:00:04.157+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:00:04.156+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:00:04.193+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:00:04.192+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:00:04.194+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:00:04.221+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.070 seconds
[2022-11-29T01:00:34.446+0000] {processor.py:156} INFO - Started process (PID=465) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:00:34.448+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:00:34.449+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:00:34.449+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:00:34.489+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:00:34.487+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:00:34.489+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:00:34.514+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.072 seconds
[2022-11-29T01:01:04.808+0000] {processor.py:156} INFO - Started process (PID=497) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:01:04.811+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:01:04.812+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:01:04.812+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:01:04.847+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:01:04.846+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:01:04.848+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:01:04.870+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T01:01:35.185+0000] {processor.py:156} INFO - Started process (PID=520) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:01:35.188+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:01:35.189+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:01:35.189+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:01:35.240+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:01:35.239+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:01:35.241+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:01:35.266+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.085 seconds
[2022-11-29T01:02:05.462+0000] {processor.py:156} INFO - Started process (PID=552) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:02:05.465+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:02:05.467+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:02:05.466+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:02:05.508+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:02:05.506+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:02:05.509+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:02:05.532+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.074 seconds
[2022-11-29T01:02:35.847+0000] {processor.py:156} INFO - Started process (PID=584) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:02:35.849+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:02:35.850+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:02:35.850+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:02:35.899+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:02:35.898+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:02:35.900+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:02:35.922+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.078 seconds
[2022-11-29T01:03:06.112+0000] {processor.py:156} INFO - Started process (PID=607) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:03:06.115+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:03:06.116+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:03:06.116+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:03:06.150+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:03:06.149+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:03:06.151+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:03:06.170+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.060 seconds
[2022-11-29T01:03:36.391+0000] {processor.py:156} INFO - Started process (PID=639) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:03:36.395+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:03:36.396+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:03:36.396+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:03:36.435+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:03:36.433+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:03:36.436+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:03:36.457+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:04:06.741+0000] {processor.py:156} INFO - Started process (PID=671) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:04:06.744+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:04:06.746+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:04:06.745+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:04:06.788+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:04:06.787+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:04:06.790+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:04:06.814+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.077 seconds
[2022-11-29T01:04:37.044+0000] {processor.py:156} INFO - Started process (PID=694) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:04:37.047+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:04:37.048+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:04:37.048+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:04:37.083+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:04:37.082+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:04:37.084+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:04:37.104+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T01:05:07.409+0000] {processor.py:156} INFO - Started process (PID=726) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:05:07.412+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:05:07.413+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:05:07.413+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:05:07.451+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:05:07.450+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:05:07.452+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:05:07.472+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.066 seconds
[2022-11-29T01:05:37.693+0000] {processor.py:156} INFO - Started process (PID=756) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:05:37.697+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:05:37.698+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:05:37.698+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:05:37.737+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:05:37.735+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:05:37.738+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:05:37.766+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.076 seconds
[2022-11-29T01:06:08.041+0000] {processor.py:156} INFO - Started process (PID=781) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:06:08.045+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:06:08.047+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:06:08.046+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:06:08.082+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:06:08.081+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:06:08.084+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:06:08.105+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.067 seconds
[2022-11-29T01:06:38.441+0000] {processor.py:156} INFO - Started process (PID=813) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:06:38.444+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:06:38.445+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:06:38.444+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:06:38.485+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:06:38.484+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:06:38.486+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:06:38.506+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.067 seconds
[2022-11-29T01:07:08.767+0000] {processor.py:156} INFO - Started process (PID=838) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:07:08.769+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:07:08.771+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:07:08.771+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:07:08.811+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:07:08.810+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:07:08.812+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:07:08.833+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:07:39.068+0000] {processor.py:156} INFO - Started process (PID=868) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:07:39.071+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:07:39.072+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:07:39.072+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:07:39.109+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:07:39.108+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:07:39.110+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:07:39.129+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T01:08:09.392+0000] {processor.py:156} INFO - Started process (PID=900) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:08:09.395+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:08:09.396+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:08:09.396+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:08:09.433+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:08:09.432+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:08:09.434+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:08:09.453+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.063 seconds
[2022-11-29T01:08:39.755+0000] {processor.py:156} INFO - Started process (PID=923) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:08:39.758+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:08:39.759+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:08:39.758+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:08:39.800+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:08:39.799+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:08:39.801+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:08:39.823+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.071 seconds
[2022-11-29T01:09:10.041+0000] {processor.py:156} INFO - Started process (PID=955) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:09:10.043+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:09:10.044+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:09:10.044+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:09:10.079+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:09:10.078+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:09:10.080+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:09:10.100+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.063 seconds
[2022-11-29T01:09:40.400+0000] {processor.py:156} INFO - Started process (PID=987) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:09:40.403+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:09:40.404+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:09:40.404+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:09:40.440+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:09:40.439+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:09:40.441+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:09:40.462+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T01:10:10.705+0000] {processor.py:156} INFO - Started process (PID=1012) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:10:10.708+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:10:10.709+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:10:10.709+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:10:10.748+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:10:10.746+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:10:10.749+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:10:10.770+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:10:41.032+0000] {processor.py:156} INFO - Started process (PID=1042) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:10:41.036+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:10:41.037+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:10:41.037+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:10:41.076+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:10:41.074+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:10:41.077+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:10:41.099+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.072 seconds
[2022-11-29T01:11:11.351+0000] {processor.py:156} INFO - Started process (PID=1074) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:11:11.354+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:11:11.355+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:11:11.355+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:11:11.396+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:11:11.395+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:11:11.397+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:11:11.418+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.070 seconds
[2022-11-29T01:11:41.743+0000] {processor.py:156} INFO - Started process (PID=1097) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:11:41.747+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:11:41.748+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:11:41.748+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:11:41.789+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:11:41.786+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:11:41.790+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:11:41.810+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:12:12.020+0000] {processor.py:156} INFO - Started process (PID=1129) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:12:12.024+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:12:12.025+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:12:12.025+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:12:12.063+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:12:12.062+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:12:12.064+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:12:12.086+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:12:42.377+0000] {processor.py:156} INFO - Started process (PID=1161) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:12:42.379+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:12:42.380+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:12:42.380+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:12:42.417+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:12:42.415+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:12:42.417+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:12:42.439+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.064 seconds
[2022-11-29T01:13:12.657+0000] {processor.py:156} INFO - Started process (PID=1184) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:13:12.661+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:13:12.662+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:13:12.662+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:13:12.696+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:13:12.695+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:13:12.697+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:13:12.779+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.125 seconds
[2022-11-29T01:13:43.007+0000] {processor.py:156} INFO - Started process (PID=1216) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:13:43.011+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:13:43.012+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:13:43.012+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:13:43.052+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:13:43.051+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:13:43.053+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:13:43.074+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.070 seconds
[2022-11-29T01:14:13.355+0000] {processor.py:156} INFO - Started process (PID=1248) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:14:13.358+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:14:13.359+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:14:13.359+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:14:13.396+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:14:13.395+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:14:13.397+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:14:13.420+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T01:14:43.643+0000] {processor.py:156} INFO - Started process (PID=1278) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:14:43.646+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:14:43.647+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:14:43.647+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:14:43.686+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:14:43.685+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:14:43.687+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:14:43.709+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:15:13.998+0000] {processor.py:156} INFO - Started process (PID=1303) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:15:14.001+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:15:14.003+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:15:14.003+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:15:14.039+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:15:14.038+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:15:14.040+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:15:14.061+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.066 seconds
[2022-11-29T01:15:44.290+0000] {processor.py:156} INFO - Started process (PID=1335) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:15:44.293+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:15:44.294+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:15:44.294+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:15:44.329+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:15:44.328+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:15:44.330+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:15:44.350+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.063 seconds
[2022-11-29T01:16:14.638+0000] {processor.py:156} INFO - Started process (PID=1358) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:16:14.641+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:16:14.642+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:16:14.642+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:16:14.683+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:16:14.681+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:16:14.683+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:16:14.703+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T01:16:45.011+0000] {processor.py:156} INFO - Started process (PID=1390) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:16:45.015+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:16:45.016+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:16:45.016+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:16:45.058+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:16:45.057+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:16:45.059+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:16:45.091+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.083 seconds
[2022-11-29T01:17:15.300+0000] {processor.py:156} INFO - Started process (PID=1423) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:17:15.303+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:17:15.304+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:17:15.304+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:17:15.341+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:17:15.340+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:17:15.342+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:17:15.361+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T01:17:45.665+0000] {processor.py:156} INFO - Started process (PID=1446) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:17:45.668+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:17:45.669+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:17:45.669+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:17:45.710+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:17:45.709+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:17:45.711+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:17:45.735+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.072 seconds
[2022-11-29T01:18:15.945+0000] {processor.py:156} INFO - Started process (PID=1478) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:18:15.948+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:18:15.949+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:18:15.949+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:18:15.986+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:18:15.984+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:18:15.987+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:18:16.011+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:18:46.323+0000] {processor.py:156} INFO - Started process (PID=1510) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:18:46.327+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:18:46.327+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:18:46.327+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:18:46.368+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:18:46.366+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:18:46.369+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:18:46.392+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.071 seconds
[2022-11-29T01:19:16.617+0000] {processor.py:156} INFO - Started process (PID=1533) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:19:16.620+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:19:16.621+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:19:16.621+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:19:16.660+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:19:16.659+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:19:16.662+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:19:16.686+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.072 seconds
[2022-11-29T01:19:46.994+0000] {processor.py:156} INFO - Started process (PID=1565) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:19:46.998+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:19:46.999+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:19:46.999+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:19:47.043+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:19:47.042+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:19:47.044+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:19:47.067+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.076 seconds
[2022-11-29T01:20:17.280+0000] {processor.py:156} INFO - Started process (PID=1597) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:20:17.283+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:20:17.284+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:20:17.284+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:20:17.324+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:20:17.323+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:20:17.325+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:20:17.346+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.070 seconds
[2022-11-29T01:20:47.638+0000] {processor.py:156} INFO - Started process (PID=1620) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:20:47.640+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:20:47.641+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:20:47.641+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:20:47.675+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:20:47.674+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:20:47.676+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:20:47.697+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.061 seconds
[2022-11-29T01:21:17.909+0000] {processor.py:156} INFO - Started process (PID=1652) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:21:17.913+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:21:17.914+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:21:17.914+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:21:17.963+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:21:17.962+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:21:17.964+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:21:17.987+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.081 seconds
[2022-11-29T01:21:48.361+0000] {processor.py:156} INFO - Started process (PID=1684) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:21:48.364+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:21:48.365+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:21:48.365+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:21:48.406+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:21:48.405+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:21:48.408+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:21:48.434+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.076 seconds
[2022-11-29T01:22:18.653+0000] {processor.py:156} INFO - Started process (PID=1707) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:22:18.656+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:22:18.657+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:22:18.657+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:22:18.695+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:22:18.694+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:22:18.696+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:22:18.717+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.066 seconds
[2022-11-29T01:22:49.008+0000] {processor.py:156} INFO - Started process (PID=1739) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:22:49.011+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:22:49.012+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:22:49.012+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:22:49.053+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:22:49.052+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:22:49.054+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:22:49.076+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.072 seconds
[2022-11-29T01:23:19.300+0000] {processor.py:156} INFO - Started process (PID=1769) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:23:19.303+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:23:19.304+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:23:19.304+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:23:19.340+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:23:19.338+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:23:19.340+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:23:19.364+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T01:23:49.648+0000] {processor.py:156} INFO - Started process (PID=1794) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:23:49.651+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:23:49.652+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:23:49.652+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:23:49.691+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:23:49.690+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:23:49.692+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:23:49.712+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.067 seconds
[2022-11-29T01:24:19.935+0000] {processor.py:156} INFO - Started process (PID=1827) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:24:19.938+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:24:19.939+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:24:19.938+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:24:19.971+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:24:19.970+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:24:19.972+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:24:20.003+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.071 seconds
[2022-11-29T01:24:50.296+0000] {processor.py:156} INFO - Started process (PID=1850) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:24:50.299+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:24:50.300+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:24:50.300+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:24:50.336+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:24:50.335+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:24:50.337+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:24:50.358+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.064 seconds
[2022-11-29T01:25:20.583+0000] {processor.py:156} INFO - Started process (PID=1882) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:25:20.586+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:25:20.587+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:25:20.587+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:25:20.626+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:25:20.624+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:25:20.627+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:25:20.648+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T01:25:50.942+0000] {processor.py:156} INFO - Started process (PID=1914) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:25:50.946+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:25:50.947+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:25:50.947+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:25:50.983+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:25:50.982+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:25:50.984+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:25:51.005+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T01:26:21.229+0000] {processor.py:156} INFO - Started process (PID=1938) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:26:21.231+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:26:21.233+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:26:21.232+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:26:21.272+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:26:21.271+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:26:21.274+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:26:21.295+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.070 seconds
[2022-11-29T01:26:51.679+0000] {processor.py:156} INFO - Started process (PID=1971) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:26:51.682+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:26:51.682+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:26:51.682+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:26:51.718+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:26:51.717+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:26:51.719+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:26:51.738+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.063 seconds
[2022-11-29T01:27:21.966+0000] {processor.py:156} INFO - Started process (PID=2003) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:27:21.970+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:27:21.972+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:27:21.972+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:27:22.012+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:27:22.011+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:27:22.013+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:27:22.036+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.073 seconds
[2022-11-29T01:27:52.335+0000] {processor.py:156} INFO - Started process (PID=2026) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:27:52.338+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:27:52.339+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:27:52.339+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:27:52.378+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:27:52.377+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:27:52.379+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:27:52.401+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T01:28:22.618+0000] {processor.py:156} INFO - Started process (PID=2058) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:28:22.621+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:28:22.622+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:28:22.622+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:28:22.660+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:28:22.659+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:28:22.661+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:28:22.682+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T01:28:52.976+0000] {processor.py:156} INFO - Started process (PID=2090) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:28:52.979+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:28:52.981+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:28:52.981+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:28:53.025+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:28:53.023+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:28:53.025+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:28:53.062+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.090 seconds
[2022-11-29T01:29:23.244+0000] {processor.py:156} INFO - Started process (PID=2113) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:29:23.247+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:29:23.248+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:29:23.248+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:29:23.285+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:29:23.284+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:29:23.286+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:29:23.307+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.066 seconds
[2022-11-29T01:29:53.509+0000] {processor.py:156} INFO - Started process (PID=2145) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:29:53.511+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:29:53.512+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:29:53.512+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:29:53.546+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:29:53.545+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:29:53.547+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:29:53.567+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.062 seconds
[2022-11-29T01:30:23.769+0000] {processor.py:156} INFO - Started process (PID=2177) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:30:23.772+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:30:23.773+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:30:23.773+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:30:23.809+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:30:23.807+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:30:23.809+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:30:23.831+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.064 seconds
[2022-11-29T01:30:54.127+0000] {processor.py:156} INFO - Started process (PID=2200) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:30:54.130+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:30:54.131+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:30:54.130+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:30:54.167+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:30:54.166+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:30:54.169+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:30:54.191+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.067 seconds
[2022-11-29T01:31:24.406+0000] {processor.py:156} INFO - Started process (PID=2232) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:31:24.409+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:31:24.410+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:31:24.410+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:31:24.450+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:31:24.447+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:31:24.452+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:31:24.477+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.075 seconds
[2022-11-29T01:31:54.839+0000] {processor.py:156} INFO - Started process (PID=2264) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:31:54.841+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:31:54.842+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:31:54.842+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:31:54.881+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:31:54.880+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:31:54.882+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:31:54.902+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.066 seconds
[2022-11-29T01:32:25.120+0000] {processor.py:156} INFO - Started process (PID=2287) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:32:25.123+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:32:25.124+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:32:25.124+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:32:25.163+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:32:25.162+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:32:25.164+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:32:25.184+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.067 seconds
[2022-11-29T01:32:55.473+0000] {processor.py:156} INFO - Started process (PID=2319) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:32:55.476+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:32:55.477+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:32:55.477+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:32:55.513+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:32:55.512+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:32:55.514+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:32:55.534+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.066 seconds
[2022-11-29T01:33:25.749+0000] {processor.py:156} INFO - Started process (PID=2351) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:33:25.752+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:33:25.753+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:33:25.753+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:33:25.790+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:33:25.787+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:33:25.790+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:33:25.810+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.064 seconds
[2022-11-29T01:33:56.100+0000] {processor.py:156} INFO - Started process (PID=2374) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:33:56.102+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:33:56.103+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:33:56.103+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:33:56.142+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:33:56.140+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:33:56.143+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:33:56.166+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:34:26.388+0000] {processor.py:156} INFO - Started process (PID=2406) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:34:26.392+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:34:26.394+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:34:26.393+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:34:26.430+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:34:26.429+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:34:26.431+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:34:26.454+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.070 seconds
[2022-11-29T01:34:56.647+0000] {processor.py:156} INFO - Started process (PID=2438) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:34:56.649+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:34:56.651+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:34:56.651+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:34:56.679+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:34:56.678+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:34:56.680+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:34:56.701+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.056 seconds
[2022-11-29T01:35:26.928+0000] {processor.py:156} INFO - Started process (PID=2462) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:35:26.931+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:35:26.932+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:35:26.932+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:35:26.970+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:35:26.968+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:35:26.971+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:35:26.991+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.067 seconds
[2022-11-29T01:35:57.271+0000] {processor.py:156} INFO - Started process (PID=2494) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:35:57.274+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:35:57.275+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:35:57.275+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:35:57.315+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:35:57.314+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:35:57.316+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:35:57.337+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:36:27.634+0000] {processor.py:156} INFO - Started process (PID=2517) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:36:27.638+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:36:27.639+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:36:27.639+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:36:27.671+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:36:27.670+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:36:27.672+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:36:27.692+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.060 seconds
[2022-11-29T01:36:57.932+0000] {processor.py:156} INFO - Started process (PID=2549) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:36:57.936+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:36:57.938+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:36:57.937+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:36:57.975+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:36:57.973+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:36:57.976+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:36:58.003+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.074 seconds
[2022-11-29T01:37:28.274+0000] {processor.py:156} INFO - Started process (PID=2582) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:37:28.278+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:37:28.279+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:37:28.279+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:37:28.316+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:37:28.314+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:37:28.317+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:37:28.339+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.067 seconds
[2022-11-29T01:37:58.583+0000] {processor.py:156} INFO - Started process (PID=2606) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:37:58.586+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:37:58.587+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:37:58.587+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:37:58.626+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:37:58.625+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:37:58.627+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:37:58.648+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T01:38:28.906+0000] {processor.py:156} INFO - Started process (PID=2638) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:38:28.910+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:38:28.911+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:38:28.911+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:38:28.947+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:38:28.946+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:38:28.948+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:38:28.971+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.070 seconds
[2022-11-29T01:38:59.227+0000] {processor.py:156} INFO - Started process (PID=2670) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:38:59.232+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:38:59.233+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:38:59.233+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:38:59.275+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:38:59.273+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:38:59.275+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:38:59.300+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.080 seconds
[2022-11-29T01:39:29.569+0000] {processor.py:156} INFO - Started process (PID=2693) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:39:29.573+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:39:29.574+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:39:29.574+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:39:29.617+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:39:29.616+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:39:29.618+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:39:29.642+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.076 seconds
[2022-11-29T01:39:59.893+0000] {processor.py:156} INFO - Started process (PID=2725) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:39:59.897+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:39:59.898+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:39:59.898+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:39:59.938+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:39:59.937+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:39:59.939+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:39:59.963+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.073 seconds
[2022-11-29T01:40:30.207+0000] {processor.py:156} INFO - Started process (PID=2757) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:40:30.210+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:40:30.211+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:40:30.211+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:40:30.245+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:40:30.243+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:40:30.246+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:40:30.270+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.065 seconds
[2022-11-29T01:41:00.540+0000] {processor.py:156} INFO - Started process (PID=2780) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:41:00.543+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:41:00.545+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:41:00.544+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:41:00.584+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:41:00.582+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:41:00.585+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:41:00.609+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.072 seconds
[2022-11-29T01:41:30.935+0000] {processor.py:156} INFO - Started process (PID=2812) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:41:30.938+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:41:30.939+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:41:30.939+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:41:30.983+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:41:30.982+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:41:30.984+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:41:31.007+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.075 seconds
[2022-11-29T01:42:01.212+0000] {processor.py:156} INFO - Started process (PID=2844) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:42:01.215+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:42:01.216+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:42:01.216+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:42:01.248+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:42:01.247+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:42:01.248+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:42:01.266+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.056 seconds
[2022-11-29T01:42:31.490+0000] {processor.py:156} INFO - Started process (PID=2867) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:42:31.493+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:42:31.495+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:42:31.494+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:42:31.533+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:42:31.532+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:42:31.534+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:42:31.555+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.068 seconds
[2022-11-29T01:43:01.835+0000] {processor.py:156} INFO - Started process (PID=2899) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:43:01.837+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:43:01.838+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:43:01.838+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:43:01.883+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:43:01.881+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:43:01.884+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:43:01.905+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.073 seconds
[2022-11-29T01:43:32.112+0000] {processor.py:156} INFO - Started process (PID=2931) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:43:32.115+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:43:32.116+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:43:32.116+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:43:32.153+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:43:32.152+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:43:32.154+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:43:32.178+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:44:02.482+0000] {processor.py:156} INFO - Started process (PID=2954) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:44:02.485+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:44:02.486+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:44:02.486+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:44:02.528+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:44:02.526+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:44:02.529+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:44:02.549+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.070 seconds
[2022-11-29T01:44:32.766+0000] {processor.py:156} INFO - Started process (PID=2986) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:44:32.769+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:44:32.771+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:44:32.771+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:44:32.808+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:44:32.807+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:44:32.809+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:44:32.832+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:45:03.109+0000] {processor.py:156} INFO - Started process (PID=3018) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:45:03.112+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:45:03.112+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:45:03.112+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:45:03.147+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:45:03.146+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:45:03.148+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:45:03.168+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.063 seconds
[2022-11-29T01:45:33.387+0000] {processor.py:156} INFO - Started process (PID=3041) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:45:33.390+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:45:33.391+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:45:33.391+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:45:33.423+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:45:33.422+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:45:33.424+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:45:33.446+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.061 seconds
[2022-11-29T01:46:03.743+0000] {processor.py:156} INFO - Started process (PID=3073) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:46:03.748+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:46:03.750+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:46:03.750+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:46:03.786+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:46:03.784+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:46:03.787+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:46:03.809+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:46:34.123+0000] {processor.py:156} INFO - Started process (PID=3105) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:46:34.127+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:46:34.128+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:46:34.128+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:46:34.164+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:46:34.163+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:46:34.165+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:46:34.190+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.069 seconds
[2022-11-29T01:47:04.404+0000] {processor.py:156} INFO - Started process (PID=3128) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:47:04.406+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:47:04.407+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:47:04.407+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:47:04.443+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:47:04.442+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:47:04.444+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:47:04.465+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.064 seconds
[2022-11-29T01:47:34.758+0000] {processor.py:156} INFO - Started process (PID=3160) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:47:34.761+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:47:34.761+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:47:34.761+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:47:34.797+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:47:34.796+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:47:34.798+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:47:34.819+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.064 seconds
[2022-11-29T01:48:05.043+0000] {processor.py:156} INFO - Started process (PID=3192) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:48:05.047+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:48:05.049+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:48:05.049+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:48:05.089+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:48:05.088+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:48:05.090+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:48:05.109+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.071 seconds
[2022-11-29T01:48:35.376+0000] {processor.py:156} INFO - Started process (PID=3215) to work on /opt/airflow/dags/create_db.py
[2022-11-29T01:48:35.379+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T01:48:35.380+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:48:35.380+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T01:48:35.415+0000] {logging_mixin.py:117} INFO - [2022-11-29T01:48:35.413+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T01:48:35.416+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T01:48:35.434+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.061 seconds
[2022-11-29T02:48:56.134+0000] {processor.py:156} INFO - Started process (PID=3241) to work on /opt/airflow/dags/create_db.py
[2022-11-29T02:48:56.138+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/create_db.py for tasks to queue
[2022-11-29T02:48:56.140+0000] {logging_mixin.py:117} INFO - [2022-11-29T02:48:56.140+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/create_db.py
[2022-11-29T02:48:56.176+0000] {logging_mixin.py:117} INFO - [2022-11-29T02:48:56.172+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/create_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_db.py", line 48
    python_callable=
                  ^
SyntaxError: invalid syntax
[2022-11-29T02:48:56.177+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/create_db.py
[2022-11-29T02:48:56.208+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/create_db.py took 0.077 seconds
